Back UP/backupfidelityshop août/src/Entity/Licence.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LicenceRepository")
 */
class Licence
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="licences")
     */
    private $vendor;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $serial;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Shop", inversedBy="licences")
     */
    private $shop;

    /**
     * @ORM\Column(type="integer")
     */
    private $terminal_id;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $pin;

    /**
     * @ORM\Column(name="periode", type="string", columnDefinition="enum('3', '6', '12')")
     */
    private $periode;

    /**
     * @ORM\Column(name="actived", type="integer")
     */
    private $actived;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $activated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $expired_at;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVendor(): ?User
    {
        return $this->vendor;
    }

    public function setVendor(?User $vendor): self
    {
        $this->vendor = $vendor;

        return $this;
    }

    public function getSerial(): ?string
    {
        return $this->serial;
    }

    public function setSerial(string $serial): self
    {
        $this->serial = $serial;

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }

    public function getTerminalId(): ?int
    {
        return $this->terminal_id;
    }

    public function setTerminalId(?int $terminal_id): self
    {
        $this->terminal_id = $terminal_id;

        return $this;
    }
    public function getActived(): ?int
    {
        return $this->actived;
    }

    public function setActived(?int $actived): self
    {
        $this->actived = $actived;

        return $this;
    }

    public function getPin(): ?string
    {
        return $this->pin;
    }

    public function setPin(?string $pin): self
    {
        $this->pin = $pin;

        return $this;
    }

    public function getPeriode(): ?string
    {
        return $this->periode;
    }

    public function setPeriode(?string $periode): self
    {
        $this->periode = $periode;

        return $this;
    }

    public function getExpiredAt()
    {
        return $this->expired_at;
    }

    public function setExpiredAt($expired_at): self
    {
        $this->expired_at = $expired_at;

        return $this;
    }
    public function getActivatedAt()
    {
        return $this->activated_at;
    }

    public function setActivatedAt($activated_at): self
    {
        $this->activated_at = $activated_at;

        return $this;
    }
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function setCreatedAt($created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }


}

Back UP/backupfidelityshop août/src/Controller/LicencesController.php
<?php

namespace App\Controller;
use App\Form\AddlicenceFormType;


use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Translation\TranslatorInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Licence;
use App\Entity\Shop;
use App\Entity\User;

class LicencesController extends AbstractController
{
    /**
     * @Route("/licences", name="licences")
     * @param UserInterface $user
     * @param Request $request
     * @return
     */
    public function index(UserInterface $user,Request $request)
    {
        $renew=false;
        if ($request->isMethod('post')) {
            $licence = $this->getDoctrine()->getRepository(Licence::class)->findOneById($request->get('licence_id'));
            $licence->setExpiredAt(new \DateTime($request->get('date_fin')));
            $licence->setActivatedAt(new \DateTime($request->get('date_debut')));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($licence);
            $entityManager->flush();
            $renew=true;
//            die(json_encode($request->get('date_fin')));
        }
    	$roles = $user->getRoles();
    	$licences_repo = $this->getDoctrine()->getRepository(Licence::class);

    	if(in_array('ROLE_ADMIN', $roles)) {
    		$licences = $licences_repo->findAll();
    	} else {
    		$licences = $user->getLicences();
    	}

    	$expired=array();

    	foreach ($licences as $licence){
    	    if($licence->getExpiredAt() != null){
                $day_diff=$licence->getExpiredAt()->getTimestamp()- (new \DateTime())->getTimestamp();
                $expired[$licence->getId()] = floor($day_diff / (60 * 60 * 24));
            }
            else{
                $expired[$licence->getId()]=0;
            }
        }

        return $this->render('licences/index.html.twig', [
            'licences' => $licences,
            'expired' => $expired,
            'renew'   => $renew
        ]);
    }

    /**
     * @Route("/licences/add", name="new_licence")
     * @param Request $request
     * @return
     */

    public function addli(Request $request)
    {
        $form_sent=false;
        $licence=new Licence();
        $form = $this->createForm(AddlicenceFormType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $licence->setSerial($this->generateLicence());
            $licence->setPeriode($form->get('periode')->getData());
//            $licence->setPin($form->get('pin')->getData());
            $licence->setPin($form->get('pin')->getData());
            $licence->setTerminalId($this->generateTerminalId());
            $licence->setCreatedAt(new \DateTime());
            $licence->setActived(0);
            $shop=$this->getDoctrine()->getRepository(Shop::class)->findOneById(
                $form->get('magasin')->getData()
            );
            $licence->setShop(
                $shop
            );
            $licence->setVendor(
                $shop->getUserId()
            );
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($licence);
            $entityManager->flush();
            $form_sent = true;
        }

        return $this->render('licences/addlicence.html.twig', [
            'addlicenceForm' => $form->createView(),
            'form_sent' => $form_sent
        ]);
    }


    private function generateLicence(){
        $characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        do{
            $randomLicence = '';
            for ($i = 1; $i <= 4; $i++) {
                for ($j = 0; $j < 5; $j++) {
                    $randomLicence .= $characters[rand(0, $charactersLength - 1)];
                }
                if($i<4)
                    $randomLicence .='-';
            }
            $licence_exist = $this->getDoctrine()->getRepository(Licence::class)->findBySerial($randomLicence);
        }while($licence_exist);
        return $randomLicence;
    }
    private function generateTerminalId(){
        $characters = '0123456789';
        $charactersLength = strlen($characters);
           do{
               $randomTerminalId = '';
               $randomTerminalId .= $characters[rand(1, $charactersLength - 1)];
                for ($j = 1; $j <= 3; $j++) {
                    $randomTerminalId .= $characters[rand(0, $charactersLength - 1)];
                }
             $licence_exist = $this->getDoctrine()
                 ->getRepository(Licence::class)->findOneBy(
                     array('terminal_id' => $randomTerminalId)
                 );

            }while($licence_exist);
        return $randomTerminalId;
    }


    /**
     * @Route("/licences/{licence}/change_status", name="change_status")
     * @param $licence
     * @return
     */
    public function activeLicence($licence) {
        $licence = $this->getDoctrine()
            ->getRepository(Licence::class)
            ->findOneById($licence);
        if($licence) {
            $licence->setActived(!$licence->getActived());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($licence);
            $entityManager->flush();
        }
        return $this->redirect($this->generateUrl('licences'));
    }

}

Back UP/backupfidelityshop août/templates/licences/addlicence.html.twig
{% extends 'base.html.twig' %}

{% block title %}Licences{% endblock %}
{% block breadcrumb_items %}<li class="active">Licences</li>{% endblock %}

{% block body_right %}

	<div class="panel panel-default table_wrapper">
		<div class="panel-heading">Licences <span class="badge badge-primary">Comptes</span>
		<a href="{{ url('licences') }}" class="btn btn-sm btn-primary float-right">Toutes les Licences</a>

		</div>
		<div class="panel-body">
		
			<h2 class="card-title">Ajouter Licence</h2>
					<div class="row">
						{{ form_start(addlicenceForm, {'attr': {
							'class': 'col-12',
							}}) }}

							<div class="form-group">
								{{ form_errors(addlicenceForm.pin) }}
 								{{ form_widget(addlicenceForm.pin, {'attr': {
									'class': 'form-control',
									'placeholder': 'Pin',
									'style' : 'display:none',
									'value'  : '1111'
								}}) }}
							</div> 
			<h6 class="card-title">Sélectionnez le magasin</h6>

						{#	<div class="form-group">
								{{ form_errors(addlicenceForm.terminal_id) }}
 								{{ form_widget(addlicenceForm.terminal_id, {'attr': {
									'class': 'form-control',
									'placeholder': 'terminal id',
									'value'  : ''
								}}) }}
							</div> #}

							<div class="form-group">
								{{ form_errors(addlicenceForm.magasin) }}
 								{{ form_widget(addlicenceForm.magasin, {'attr': {
									'class': 'form-control',
								}}) }}
							</div>

			<h6 class="card-title">Choissisez la période de validité</h6>


							<div class="form-group">
								{{ form_errors(addlicenceForm.periode) }}
 								{{ form_widget(addlicenceForm.periode, {'attr': {
									'class': 'form-control',
									
								}}) }}
							</div>

							

						
						
					</div>


		<div class="panel panel-default table_wrapper">
		<a href="{{ url('licences') }}" class="btn btn-sm btn-primary float-right">Retour</a>
							<button type="submit"  class="btn btn-primary float-left">Ajouter</button>
						{{ form_end(addlicenceForm) }}

		</div>


		</div>
	</div>

{% endblock %}

Back UP/backupfidelityshop août/templates/licences/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Licences{% endblock %}
{% block breadcrumb_items %}<li class="active">Licences</li>{% endblock %}

{% block body_right %}

	<div class="panel panel-default table_wrapper">
		<div class="panel-heading">Licences <span class="badge badge-primary">{{ licences|length }}</span>
		<a href="{{ url('new_licence') }}" class="btn btn-sm btn-primary float-right">Ajouter Licence</a>


		</div>
		<div class="panel-body">
			<table class="table table-striped text-center">
				<thead>
					<tr>
						<th>ID</th>
						<th>Clé de licence</th>
						<th>Magasin associé</th>
						<th>Terminal</th>
						<th>Periode</th>
						<th>Date d'activation</th>
						<th>Expiration</th>
						<th>
							Renouveler
						</th>
						<!--th>Code pin</th-->
						<th>Etat</th>
					</tr>
				</thead>
				<tbody>
					{% for licence in licences %}
						<tr>
							<th>{{ licence.id }}</th>
							<th>{{ licence.serial }}</th>
							<th><a href="{{ url('single_shop', {'id': licence.shop.id}) }}">{{ licence.shop.name }}</a></th>
							<th>ID{{ licence.terminalId }}</th>
							<th>{{licence.periode}} Mois</th>	
							
							<th>{% if licence.actived == 1 %}<h6> {{licence.activatedAt|date('d/m/Y')}} </h6>
							{% endif %}
							</th>			
							<th>
							{# endDate and startDate are strings or DateTime objects #}
							<h6>
							{%  if licence.expiredAt is not null %}
								{% if expired[licence.id] < -1  %}
									<span class="label label-danger" style="color:#fff;padding:5px;border-radius:5px">
									Expire le {{licence.expiredAt|date('d/m/Y')}}
									
								{% elseif expired[licence.id] <=7 and expired[licence.id] >= -1 %}
									<span class="label label-warning" style="color:#fff;padding:5px;border-radius:5px">
							    	{{licence.expiredAt|date('d/m/Y')}}
								{% else %}
									<span class="label label-success" style="color:#fff;padding:5px;border-radius:5px">
							    	{{licence.expiredAt|date('d/m/Y')}}
								{% endif %}
							{% else %}
								<span class="label label-default" style="color:#fff;padding:5px;border-radius:5px">
								 n'est pas encore activé
							{% endif %}
							</span>
							</h6>
							</th>
							<th>
							{% if expired[licence.id] < -1  %}
							<i class="fa fa-sync" onclick="renew({{licence.id}});" style="color:#76FF03;font-size:130%;cursor:pointer"></i>
							{% endif %}
							</th>
							<!--th>{{ licence.pin }}</th-->
							<th>
							<a href="{{ url('change_status', {'licence': licence.id}) }}">
							{% if licence.actived %}
							<i class="fa fa-circle" style="color:#76ff03;font-size:130%"></i>
							{% else %}
							<i class="fa fa-circle" style="color:#d50000;font-size:130%"></i>
							{% endif %}
							</th>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}

{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.33.1/sweetalert2.min.js"></script>
<script>


var renew_ ="{{renew}}";


if(renew_){
	Swal.fire({
        title: "Félécitation",
        type: "success",
		text: "la licence a été renouvelé par succès",
        showCancelButton: false, 
        confirmButtonColor: "#30a5ff",
        cancelButtonColor: "#d33",
        confirmButtonText: "Continuer",
        cancelButtonText: "ANNULER",
        allowOutsideClick: false,
    }).then(result => {
    });
}


function renew(licence_id){
	Swal.fire({
        type: "info",
        html:
		'<div class="col-md-12 col-sm-12">'+
         '   <div class="card">'+
          '      <div class="card-body">'+
           '         <h2 class="card-title">Renouveler Licence</h2>'+
            '             <form action="https://fidelityshop.be/connexion/public/licences" method="post">'+
             '           <input type="hidden" name="_csrf_token" value="nEp3mNI7H9r-zkFgnIr2xO9e4QmXgTRHRtJDFOexZPs">'+
			  '           <input type="hidden" value="'+licence_id+'" name="licence_id" value="nEp3mNI7H9r-zkFgnIr2xO9e4QmXgTRHRtJDFOexZPs">'+
              '          <div class="input-group">'+
		'					<div class="input-group-prepend">'+
		' <span class="input-group-text" id="date_debut">Date Debut</span>'+
                '</div><input type="date" name="date_debut" required>'+
		'				</div>'+
         '               <div class="input-group">'+
		'					<div class="input-group-prepend">'+
		' <span class="input-group-text" id="date_fin">Date fin</span>'+
                '</div><input type="date" name="date_fin" required>'+
		'				</div>'+
         '               <button type="submit" id="sendlogin" class="btn btn-primary float-right">Renouveler</button>'+
          '          </form>'+
           '     </div>'+
            '</div>'+
        '</div>',
        showCancelButton: false,
        confirmButtonColor: "#d33",
        cancelButtonColor: "#d33",
        confirmButtonText: "ANNULER ",
        cancelButtonText: "ANNULER",
        allowOutsideClick: false,
    }).then(result => {
    });
}

</script>
{% endblock %}